name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'Releases'
    labels:
      - 'release'
      - 'publish'
  - title: 'Work in Progress'
    labels:
      - 'wip'
      - 'docs'
      - 'doc'
      - 'research'
      - 'learn'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'typo'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'feat'
      - 'feature'
      - 'clean'
exclude-labels:
  - 'skip-changelog'
  - 'skip'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ### Changes

  $CHANGES
