name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'Release'
    labels:
      - 'PR: Publishing'
  - title: 'Work in Progress'
    labels:
      - 'PR: Writing'
      - 'PR: Editing'
  - title: 'Corrections'
    labels:
      - 'PR: Correction'
  - title: 'Development'
    labels:
      - 'PR: Background'
exclude-labels:
  - 'fix-b60205'
  - 'PR: Skip'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ### Changes

  $CHANGES
