a430d730aa1cf0f9302d5ef5baaced4e:
  body: ''
  location: ./src/0101-discovery/001-introduce-ephraim.md
  title: New Issue without body
  number: 116
d1ec22f0f75e98f4909d9f6a9cc5f345:
  body: ''
  location: ./src/0101-discovery/001-introduce-ephraim.md
  title: Existing issue
  number: 116
