#!/Users/merovex/.rvm/rubies/ruby-2.4.1/bin/ruby

require 'fileutils'


action = ARGV.shift
target = ARGV.shift || 'text'

images_dir = "#{target}/images/"
css_file = "style.css"
version = `git describe --abbrev=0 --tags` || 'none'
metadata = "metadata.yml"
build_flags = {}
templates_dir = "#{Dir.home}/.verkilorc/templates/"


build_flags[:epub] = <<-HEREDOC \
--epub-cover-image=#{images_dir}cover.png \
--css=#{templates_dir}#{css_file} \
--template=#{templates_dir}epub.html \
--metadata-file=#{metadata} \
--metadata=version:#{version} \
--lua-filter #{templates_dir}latex.lua \
--toc --toc-depth=2 \
--webtex
HEREDOC

build_flags[:html] = <<-HEREDOC \
--css=#{templates_dir}#{css_file} \
--standalone --to=html5 \
--metadata-file=#{metadata} \
--lua-filter #{templates_dir}latex.lua \
--toc --toc-depth=2 \
--self-contained \
--webtex
HEREDOC

build_flags[:pdf] = <<-HEREDOC \
  -V documentclass=book \
--template=#{templates_dir}pdf.tex \
--metadata-file=#{metadata} \
--metadata=version:#{version} \
--lua-filter #{templates_dir}latex.lua \
--pdf-engine=xelatex \
--toc --toc-depth=2 \
--webtex
HEREDOC
#
build_flags[:docx] = <<-HEREDOC \
  --reference-doc=#{templates_dir}reference.docx \
  --metadata-file=#{metadata} \
  --lua-filter #{templates_dir}latex.lua
HEREDOC

basename = "#{File.basename(Dir.pwd)}-#{target}"
build_dir = (action == "html") ? "build/html/" : "build/"

if %w(pdf docx epub html).include?(action)

  FileUtils.mkdir_p(build_dir)

  output_filename = "#{build_dir}#{basename}.#{action}"
  chapters        = Dir["#{target}/**/*.md"].sort.first #.join(" ")

  args = "#{build_flags[action.to_sym]} -o #{output_filename} #{chapters}".gsub(/\s+/, " ")

  puts "pandoc #{args}"
  puts `pandoc #{args}`
elsif (action == 'clean')
  FileUtils.rm_rf(build_dir)
end
