# Name: Compile Readme
#
# Description: This Github Action runs on each push to dynamically build
# the repository's README based on the template and other Markdown files
# In the repository.
# =================================================
name: Compile Readme
on: [push]
jobs:
  build:
    if: "contains(toJSON(github.event.commits.*.message), '@verkilo readme')"
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@main
        with:
          ref: master
      - name: Compile
        uses: docker://merovex/readme-writer:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        run: |
          git config --global user.email "ben@merovex.com"
          git config --global user.name "Ben W"
          git commit -am "Rebuilt README from contents"
          git push origin $(git symbolic-ref HEAD | cut -d'/' -f3)
