# Name: Compile Book
#
# Description: This Circle CI action automates compiling the various works-in-progress
# managed in this repository. It uses a custom-built Docker container to checkout the
# repository, compile, and push the resulting artifacts to the current month's Release
# on Github.
# =================================================
version: 2.1
jobs:
  build:
    docker:
      - image: merovex/pandoc-book-compile:latest
    steps:
      - checkout
      - run:
          name: Compile Book
          command: |
            pandoc-book.rb ${CIRCLE_PROJECT_REPONAME}
            mkdir -p /tmp/builds
            cp -r build/* /tmp/builds
            
      - run:
          name: Deploy to Github
          command: |
            VERSION=v$(date '+%y.%m')
            echo ${VERSION}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/builds/
