# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

venue: Virginia
title: Horatio Beech, Author
firstname: Horatio
fullname: Horatio Beech
email: me@horatiobeech.com
description: >- # this means to ignore newlines until "baseurl:"
  Horatio Beech is the author of the Strand Series, a low fantasy, Type-X alternative-history novel/novella series. Eighteenth-Century British-Americans discovered advanced technology in the Ohio Territory at the end of the Seven Year's War.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://horatiobeech.com/" # the base hostname & protocol for your site, e.g. http://example.com
email: me@horatiobeech.com

social_media:
  # behance: your_username
  # dribbble: your_username  
  facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

mailchimp: https://dausha.us2.list-manage.com/subscribe/post?u=958ff43d5b0de49bac9ad4e21&amp;id=72de3b22a5
mailchimp_bot: b_958ff43d5b0de49bac9ad4e21_72de3b22a5

licenses:
  CC0:
    tag: "CC0"
    url: "https://creativecommons.org/share-your-work/public-domain/cc0/"
  PD:
    tag: "Public Domain"
    url: "https://creativecommons.org/share-your-work/public-domain/cc0/"
  RR:
    tag: "Rights Reserved"
    url: "#"
  BY:
    tag: "CC BY 2.0"
    url: "https://creativecommons.org/licenses/by/2.0/"
  BY-SA:
    tag: "CC BY-SA 2.0"
    url: "https://creativecommons.org/licenses/by-sa/2.0/"
  BY-ND:
    tag: "CC BY-ND 2.0"
    url: "https://creativecommons.org/licenses/by-nd/2.0/"

# Build settings
permalink: /posts/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo

collections:
  books:
    output: true
    permalink: /books/:path/

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
kramdown:
  input                   : GFM
  hard_wrap               : false
  auto_ids                : true
  footnote_nr             : 1
  entity_output           : as_char
  toc_levels              : 2..4
  smart_quotes            : lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    disable               : true
