name: Book Builder

on: [release]

jobs:
  build:
    name: Build the Book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Pandoc Book (Docker)
        uses: docker://merovex/pandoc-book:latest
      - name: Zip it.
        run: zip books build
      - uses: actions/upload-artifact@v1
        with:
          name: "books"
          path: build
      - name: Upload Release Asset
        id: upload-release-asset
        uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: books.zip application/zip
