name: Book Builder

on: [push]

jobs:
  build:
    name: Build the Book
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v1
      - name: Run Pandoc Book (Docker)
        uses: docker://merovex/pandoc-book:latest
      - id: getfilename
        run: echo "::set-output name=file::$(ls build/*.*)"
      - uses: actions/upload-artifact@v1
        with:
          name: "books"
          path: build

#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
#     - name: Upload artifact
#       uses: actions/upload-artifact@v1.0.0
#       with:
#         # Artifact name
#         name:
#         # Directory containing files to upload
#         path:
