
name: Compile Books
on: [push]
# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - master

jobs:
  job_1:
    name: Build the Books
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v1
      - name: Run Pandoc Book (Docker)
        uses: docker://merovex/book-compiler:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive books
        uses: actions/upload-artifact@v1
        with:
          name: stranded-series
          path: build
  job_2:
    name: Release Books
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: stranded-series
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: test-tag
      #     release_name: Release ${{ github.ref }}
      #     draft: true
      #     prerelease: false
      - name: Upload Artifacts to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/runner/work/stranded-series/stranded-series/stranded-series/*"
          tag: test-tag
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
