
name: Compile Books
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    name: Build the Books
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v1
      - name: Run Pandoc Book (Docker)
        uses: docker://merovex/pandoc-book-compile:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
