
name: Revision Issues Maintainer (on Demand)
on: [push]
jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '@verkilo logged revision issues')"
    name: Log revision issues
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@main
        with:
          ref: main
      - name: Run bot (Docker)
        uses: docker://merovex/revision-issue-bot:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        run: |
          git config --global user.email "ben@merovex.com"
          git config --global user.name "Ben W"
          git commit -am "@verkilo logged revision issues"
          git push origin $(git symbolic-ref HEAD | cut -d'/' -f3)
