name: Maintain Version (Push)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Version Tag
        run: |
          VERSION=v$(date '+%y.%m')
          git tag ${VERSION}
          git push origin ${VERSION}
