name: Optimize Images
on: [push]
jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '@verkilo optimized images')"
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@master
        with:
          ref: main
      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
      - name: Echo file changes
        run: |
          echo Changed files: ${{ steps.get_file_changes.outputs.files }}
      - name: Optimize
        uses: docker://merovex/optimize-image-bot:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit on change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "@verkilo optimized images"
