
name: Proof Books
on: [push]
jobs:
  build:
    if: "contains(toJSON(github.event.commits.*.message), 'proof')"
    name: Compile books
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v1
      - name: Run Pandoc Book (Docker)
        uses: docker://merovex/book-compiler:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: strand-series
          path: build
