
name: Proof Books
on: [push]
jobs:
  build:
    if: "contains(toJSON(github.event.commits.*.message), '@verkilo proof')"
    name: Compile books
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v1
      - name: Run compiler (Docker)
        uses: docker://merovex/verkilo:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION: compile
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: stranded-series
          path: build
